# Binance Spot Testnet market stream and WebSocket API.
stream_url = "wss://stream.testnet.binance.vision/ws"
ws_api_url = "wss://ws-api.testnet.binance.vision/ws-api/v3"
# Binance Spot Testnet REST API.
api_url = "https://testnet.binance.vision"

order_prefix = "test"
api_key = ""
secret = ""
